#pragma once
#include <lvgl.h>

/**
 * Noto Sans KR 12px — Korean syllables (가-힣)
 * Used as fallback for lv_font_montserrat_12 to render Korean text.
 * Generated by lv_font_conv, BPP 4
 */
LV_FONT_DECLARE(font_noto_kr_12);
